export type RsvpStatus = "going" | "maybe" | "not_going";

export interface FamilyMember {
  id: string;
  name: string;
  avatar_emoji: string;
  color: string;
  sort_order: number;
  created_at: string;
  /** Storage object path in the `family-media` bucket, or null for emoji-only. */
  avatar_path: string | null;
}

/** A member plus the short-lived signed URL for their photo. */
export interface MemberWithPhoto extends FamilyMember {
  avatar_url: string | null;
}

export interface FamilyEvent {
  id: string;
  title: string;
  description: string | null;
  location: string | null;
  event_date: string;
  created_by: string | null;
  created_at: string;
}

export interface EventRsvp {
  event_id: string;
  member_id: string;
  status: RsvpStatus;
  updated_at: string;
}

export interface CalendarEntry {
  id: string;
  member_id: string | null;
  title: string;
  start_time: string;
  end_time: string | null;
  category: string;
  created_at: string;
  source_feed_id: string | null;
  source_uid: string | null;
  all_day: boolean;
}

export type AttachmentKind = "image" | "voice" | "file";

export interface Message {
  id: string;
  sender_id: string | null;
  message_text: string;
  created_at: string;
  attachment_path: string | null;
  attachment_kind: AttachmentKind | null;
  attachment_name: string | null;
  attachment_mime: string | null;
  attachment_size: number | null;
  /** Seconds. Voice notes only. */
  attachment_duration: number | null;
  /** Set when someone removes the message; the row is kept as a tombstone. */
  deleted_at: string | null;
  deleted_by: string | null;
  /** Null for the group thread; a member id for a direct message. */
  recipient_id: string | null;
  /**
   * Generated by Postgres: the two member ids sorted and joined, so both
   * directions of a conversation share one key. Null for the group thread.
   *
   * Read-only — the column is `generated always`, and an insert that names it
   * is rejected outright, not merely ignored.
   */
  conversation_key: string | null;
}

/**
 * Which thread is on screen: `null` is the group, a member id is a one-to-one
 * conversation with that person.
 *
 * These are *not* private in the security sense. There is no login, so the
 * filtering is a query the client asks for rather than a rule the database
 * enforces — see the Security model section of the README, and the header of
 * migration 0006.
 */
export type ConversationId = string | null;

/** The group thread needs a name to be used as a Record key. */
export const GROUP_CONVERSATION = "group";

/**
 * Names the thread a message belongs to, for cache and read-mark bookkeeping.
 *
 * For a DM this is the database's `conversation_key`: the two ids sorted and
 * joined, so both directions agree. The sort must match migration 0006's
 * generated column exactly or a thread reads as empty — 0006 compares as
 * `uuid`, which is byte order, and Supabase hands out canonical lowercase
 * UUIDs, so a plain JS compare over two equal-length strings of [0-9a-f-]
 * gives the same answer without a collation in sight.
 */
export function conversationKeyFor(
  senderId: string,
  recipientId: string | null,
): string {
  if (!recipientId) return GROUP_CONVERSATION;
  return senderId < recipientId
    ? `${senderId}:${recipientId}`
    : `${recipientId}:${senderId}`;
}

/**
 * The closed reaction palette. Widening this array is not enough on its own —
 * `family_message_reactions` has a matching check constraint, so the migration
 * has to agree before a new emoji will insert.
 */
export const REACTION_EMOJI = ["👍", "❤️", "😂"] as const;
export type ReactionEmoji = (typeof REACTION_EMOJI)[number];

export interface MessageReaction {
  message_id: string;
  member_id: string;
  emoji: ReactionEmoji;
  created_at: string;
}

/** One emoji's tally on one message, resolved for rendering. */
export interface ReactionSummary {
  emoji: ReactionEmoji;
  memberIds: string[];
  mine: boolean;
}

/** One line on the shared shopping list. */
export interface ShoppingItem {
  id: string;
  name: string;
  /** Free text: "2 boxes", "the big one". Never a number. */
  note: string | null;
  added_by: string | null;
  created_at: string;
  /** Null means still to buy. Set means done — that is the whole state. */
  completed_at: string | null;
  completed_by: string | null;
}

export interface Quote {
  id: string;
  quote_text: string;
  author: string | null;
  is_active: boolean;
}

export interface LookingForward {
  member_id: string;
  note: string;
  target_date: string | null;
  updated_at: string;
}

export interface CalendarFeed {
  id: string;
  member_id: string | null;
  name: string;
  /**
   * Whether this feed has a live URL, as opposed to a one-off pasted import.
   *
   * The URL itself is deliberately absent: it is a *secret* calendar address,
   * and migration 0004 revokes SELECT on that column from the browser's role.
   * A generated column answers the only question the UI ever asked of it.
   */
  has_url: boolean;
  is_active: boolean;
  last_synced_at: string | null;
  last_error: string | null;
  last_event_count: number | null;
  created_at: string;
}

/** Anything that can land on the aggregated calendar. */
export type AgendaKind = "event" | "entry";

export interface AgendaItem {
  id: string;
  kind: AgendaKind;
  title: string;
  subtitle?: string | null;
  /** Local `YYYY-MM-DD` the item belongs to. */
  day: string;
  /** Null for all-day items. */
  start: Date | null;
  end: Date | null;
  memberIds: string[];
  allDay?: boolean;
  /** Imported from a calendar feed — deleting it here would just resync back. */
  readOnly?: boolean;

  /*
   * Everything below exists only for the detail sheet. The agenda row is a
   * one-line summary and deliberately shows none of it — but a row that can be
   * opened has to carry what opening it reveals, and the alternative (looking
   * the source row back up by id) would mean the sheet re-deriving the join
   * `buildAgenda` already did.
   */

  /** Entries only. `general` is treated as "uncategorised" and not shown. */
  category?: string | null;
  /** Events only. */
  location?: string | null;
  /** Events only — never surfaced anywhere in the UI before the detail sheet. */
  description?: string | null;
}

/**
 * One chore, ticked off for one period. The chore itself is defined in
 * `lib/chores.ts` — this row only records that it happened, so the roster can
 * be reworded without touching history.
 *
 * `period_key` is a local day (`2026-08-24`) for daily chores and an ISO week
 * (`2026-W35`) for weekly ones. Which of the two a chore uses comes from its
 * cadence, so the key is derived on the client rather than stored per row.
 */
export interface ChoreTick {
  chore_key: string;
  period_key: string;
  done_by: string | null;
  done_at: string;
}

/** A photo on the family wall, plus the short-lived signed URL for it. */
export interface FamilyPhoto {
  id: string;
  storage_path: string;
  caption: string | null;
  uploaded_by: string | null;
  created_at: string;
}

export interface PhotoWithUrl extends FamilyPhoto {
  url: string | null;
}
