-- ============================================================================
--  Family Dashboard — schema, rotation engine, RLS and realtime
--  Run this in the Supabase SQL Editor (or `supabase db push`).
--
--  This project shares a Supabase database with other apps, so every object
--  is namespaced with a `family_` prefix, matching the existing convention
--  (`life_flow_*`, `myday_*`, `alux_*`).
--
--  Idempotent: safe to re-run.
-- ============================================================================

create extension if not exists "pgcrypto";

-- ---------------------------------------------------------------------------
-- Enums
-- ---------------------------------------------------------------------------
do $$ begin
  create type public.family_recurrence as enum ('daily', 'weekly');
exception when duplicate_object then null; end $$;

do $$ begin
  create type public.family_rsvp_status as enum ('going', 'maybe', 'not_going');
exception when duplicate_object then null; end $$;

-- ---------------------------------------------------------------------------
-- family_members — the 5 people. Everything else points here.
-- ---------------------------------------------------------------------------
create table if not exists public.family_members (
  id           uuid primary key default gen_random_uuid(),
  name         text not null check (length(trim(name)) between 1 and 40),
  avatar_emoji text not null default '🙂',
  color        text not null default '#6366f1'
                 check (color ~ '^#[0-9a-fA-F]{6}$'),
  sort_order   integer not null default 0,
  created_at   timestamptz not null default now()
);

-- ---------------------------------------------------------------------------
-- family_chore_templates — the *definition* of a recurring chore.
-- `family_chores` rows are the per-period instances generated from these.
-- `rotation_offset` staggers who starts on which chore so that two people
-- are never handed the same job on day one.
-- ---------------------------------------------------------------------------
create table if not exists public.family_chore_templates (
  id              uuid primary key default gen_random_uuid(),
  title           text not null,
  description     text,
  recurrence_type public.family_recurrence not null default 'daily',
  rotation_offset integer not null default 0,
  is_active       boolean not null default true,
  sort_order      integer not null default 0,
  created_at      timestamptz not null default now()
);

-- ---------------------------------------------------------------------------
-- family_chores — one row per (chore, period). Generated by
-- `family_generate_chores()`; ticked off by whoever does the job.
-- ---------------------------------------------------------------------------
create table if not exists public.family_chores (
  id                 uuid primary key default gen_random_uuid(),
  template_id        uuid references public.family_chore_templates(id) on delete cascade,
  title              text not null,
  description        text,
  recurrence_type    public.family_recurrence not null,
  assigned_member_id uuid references public.family_members(id) on delete set null,
  is_completed       boolean not null default false,
  completed_at       timestamptz,
  completed_by       uuid references public.family_members(id) on delete set null,
  due_date           date not null,
  -- 'd:2026-08-21' for daily, 'w:2026-W34' for weekly. Together with
  -- template_id this is what makes generation idempotent.
  period_key         text not null,
  created_at         timestamptz not null default now(),
  unique (template_id, period_key)
);

create index if not exists family_chores_due_date_idx  on public.family_chores (due_date);
create index if not exists family_chores_assignee_idx  on public.family_chores (assigned_member_id, due_date);

-- ---------------------------------------------------------------------------
-- family_events — the activity board (movies, CNE, trips downtown…)
-- ---------------------------------------------------------------------------
create table if not exists public.family_events (
  id          uuid primary key default gen_random_uuid(),
  title       text not null check (length(trim(title)) between 1 and 120),
  description text,
  location    text,
  event_date  timestamptz not null,
  created_by  uuid references public.family_members(id) on delete set null,
  created_at  timestamptz not null default now()
);

create index if not exists family_events_date_idx on public.family_events (event_date);

-- Attendees, normalised so the RSVP checklist can hold a real per-person state
-- rather than a flat array.
create table if not exists public.family_event_rsvps (
  event_id   uuid not null references public.family_events(id) on delete cascade,
  member_id  uuid not null references public.family_members(id) on delete cascade,
  status     public.family_rsvp_status not null default 'going',
  updated_at timestamptz not null default now(),
  primary key (event_id, member_id)
);

-- ---------------------------------------------------------------------------
-- family_calendar_entries — per-member personal schedule items that show up
-- on the shared calendar alongside events and chore deadlines.
-- ---------------------------------------------------------------------------
create table if not exists public.family_calendar_entries (
  id         uuid primary key default gen_random_uuid(),
  member_id  uuid references public.family_members(id) on delete cascade,
  title      text not null check (length(trim(title)) between 1 and 120),
  start_time timestamptz not null,
  end_time   timestamptz,
  category   text not null default 'general',
  created_at timestamptz not null default now(),
  check (end_time is null or end_time >= start_time)
);

create index if not exists family_calendar_start_idx on public.family_calendar_entries (start_time);

-- ---------------------------------------------------------------------------
-- family_messages — the group chat.
-- ---------------------------------------------------------------------------
create table if not exists public.family_messages (
  id           uuid primary key default gen_random_uuid(),
  sender_id    uuid references public.family_members(id) on delete cascade,
  message_text text not null check (length(trim(message_text)) between 1 and 2000),
  created_at   timestamptz not null default now()
);

create index if not exists family_messages_created_idx on public.family_messages (created_at desc);

-- ============================================================================
--  Rotation engine
--  Materialises chore instances for a window of days, assigning each one to
--  the next member in line. Rotation is *deterministic*: it is a function of
--  the period number, so re-running never reshuffles history, and every
--  device computes the same answer.
-- ============================================================================
create or replace function public.family_generate_chores(
  p_from date default current_date,
  p_days integer default 14
)
returns integer
language plpgsql
security invoker
set search_path = public
as $$
declare
  v_members   uuid[];
  v_count     integer;
  v_day       date;
  v_tpl       record;
  v_period    text;
  v_due       date;
  v_index     bigint;
  v_week_mon  date;
  v_inserted  integer := 0;
begin
  select array_agg(id order by sort_order, created_at, id)
    into v_members
    from public.family_members;

  v_count := coalesce(array_length(v_members, 1), 0);
  if v_count = 0 then
    return 0;  -- nobody set up yet
  end if;

  for v_day in
    select generate_series(p_from, p_from + (greatest(p_days, 1) - 1), interval '1 day')::date
  loop
    for v_tpl in
      select * from public.family_chore_templates where is_active order by sort_order, id
    loop
      if v_tpl.recurrence_type = 'daily' then
        v_due    := v_day;
        v_period := 'd:' || to_char(v_day, 'YYYY-MM-DD');
        -- 1970-01-05 is a Monday, so this counts days from a week boundary.
        v_index  := v_day - date '1970-01-05';
      else
        v_week_mon := date_trunc('week', v_day)::date;   -- ISO week starts Monday
        v_due      := v_week_mon + 6;                    -- weekly jobs are due Sunday
        v_period   := 'w:' || to_char(v_week_mon, 'IYYY-"W"IW');
        v_index    := (v_week_mon - date '1970-01-05') / 7;
      end if;

      insert into public.family_chores (
        template_id, title, description, recurrence_type,
        assigned_member_id, due_date, period_key
      )
      values (
        v_tpl.id, v_tpl.title, v_tpl.description, v_tpl.recurrence_type,
        v_members[ ((v_index + v_tpl.rotation_offset) % v_count) + 1 ],
        v_due, v_period
      )
      on conflict (template_id, period_key) do nothing;

      if found then
        v_inserted := v_inserted + 1;
      end if;
    end loop;
  end loop;

  return v_inserted;
end;
$$;

-- Toggling a chore should stamp/clear the audit columns atomically.
create or replace function public.family_set_chore_done(
  p_chore_id uuid,
  p_done boolean,
  p_member_id uuid default null
)
returns public.family_chores
language sql
security invoker
set search_path = public
as $$
  update public.family_chores
     set is_completed = p_done,
         completed_at = case when p_done then now() else null end,
         completed_by = case when p_done then p_member_id else null end
   where id = p_chore_id
  returning *;
$$;

-- ============================================================================
--  Row Level Security
--
--  NOTE: this dashboard has no login — you pick your face from a list, exactly
--  as specified. That means the browser only ever holds the anon key, so these
--  policies necessarily grant the anon role access to the family_* tables.
--  Anyone who has both the project URL and the anon key can read and write
--  this family's data. See README ("Security model") for how to lock it down
--  with Supabase Auth later. RLS stays ON so that the policy surface is
--  explicit and scoped to these tables only — the other apps sharing this
--  database are unaffected.
-- ============================================================================
alter table public.family_members          enable row level security;
alter table public.family_chore_templates  enable row level security;
alter table public.family_chores           enable row level security;
alter table public.family_events           enable row level security;
alter table public.family_event_rsvps      enable row level security;
alter table public.family_calendar_entries enable row level security;
alter table public.family_messages         enable row level security;

do $$
declare
  t text;
begin
  foreach t in array array[
    'family_members', 'family_chore_templates', 'family_chores',
    'family_events', 'family_event_rsvps', 'family_calendar_entries',
    'family_messages'
  ] loop
    execute format('drop policy if exists %I on public.%I', t || '_family_access', t);
    execute format(
      'create policy %I on public.%I for all to anon, authenticated using (true) with check (true)',
      t || '_family_access', t
    );
  end loop;
end $$;

-- ============================================================================
--  Realtime — messages and chores stream to every device.
--  FULL replica identity so UPDATE/DELETE payloads carry the old row, which
--  is what lets the client reconcile a chore toggle it did not originate.
-- ============================================================================
alter table public.family_messages replica identity full;
alter table public.family_chores   replica identity full;

do $$
begin
  alter publication supabase_realtime add table public.family_messages;
exception when duplicate_object then null; end $$;

do $$
begin
  alter publication supabase_realtime add table public.family_chores;
exception when duplicate_object then null; end $$;

-- ============================================================================
--  Seed: the default chore roster from the spec.
--  Family members are created from the app's first-run setup screen, so no
--  placeholder people are inserted here.
-- ============================================================================
insert into public.family_chore_templates (title, description, recurrence_type, rotation_offset, sort_order)
select v.title, v.description, v.recurrence_type::public.family_recurrence, v.rotation_offset, v.sort_order
from (values
  ('Wipe the counters',   'Kitchen counters and the dining table after dinner.', 'daily',  0, 1),
  ('Wash the dishes',     'Everything in the sink, plus scrub the pots.',        'daily',  1, 2),
  ('Put away the dishes', 'Empty the drying rack and the dishwasher.',           'daily',  2, 3),
  ('Take out the trash',  'Kitchen bin, plus recycling on collection nights.',   'daily',  3, 4),
  ('Vacuum the house',    'Living room, hallway and the stairs.',                'weekly', 0, 5),
  ('Mop the floors',      'Kitchen and both bathrooms.',                         'weekly', 2, 6)
) as v(title, description, recurrence_type, rotation_offset, sort_order)
where not exists (
  select 1 from public.family_chore_templates t where t.title = v.title
);
